package com.wmods.wppenhacer.xposed.features.others

/** Google NMT language catalog, retrieved 2026-09-11.
 * https://docs.cloud.google.com/translate/docs/languages
 * The existing consumer GTX endpoint may not support every Cloud language.
 */
internal object GoogleTranslateLanguages {
    val entries = listOf(
        "ab" to "Abkhaz",
        "ace" to "Acehnese",
        "ach" to "Acholi",
        "af" to "Afrikaans",
        "sq" to "Albanian",
        "alz" to "Alur",
        "am" to "Amharic",
        "ar" to "Arabic",
        "hy" to "Armenian",
        "as" to "Assamese",
        "awa" to "Awadhi",
        "ay" to "Aymara",
        "az" to "Azerbaijani",
        "ban" to "Balinese",
        "bm" to "Bambara",
        "ba" to "Bashkir",
        "eu" to "Basque",
        "btx" to "Batak Karo",
        "bts" to "Batak Simalungun",
        "bbc" to "Batak Toba",
        "be" to "Belarusian",
        "bem" to "Bemba",
        "bn" to "Bengali",
        "bew" to "Betawi",
        "bho" to "Bhojpuri",
        "bik" to "Bikol",
        "bs" to "Bosnian",
        "br" to "Breton",
        "bg" to "Bulgarian",
        "bua" to "Buryat",
        "yue" to "Cantonese",
        "ca" to "Catalan",
        "ceb" to "Cebuano",
        "ny" to "Chichewa (Nyanja)",
        "zh-CN" to "Chinese (Simplified)",
        "zh-TW" to "Chinese (Traditional)",
        "cv" to "Chuvash",
        "co" to "Corsican",
        "crh" to "Crimean Tatar",
        "hr" to "Croatian",
        "cs" to "Czech",
        "da" to "Danish",
        "din" to "Dinka",
        "dv" to "Divehi",
        "doi" to "Dogri",
        "dov" to "Dombe",
        "nl" to "Dutch",
        "dz" to "Dzongkha",
        "en" to "English",
        "eo" to "Esperanto",
        "et" to "Estonian",
        "ee" to "Ewe",
        "fj" to "Fijian",
        "fil" to "Filipino (Tagalog)",
        "fi" to "Finnish",
        "fr" to "French",
        "fr-FR" to "French (French)",
        "fr-CA" to "French (Canadian)",
        "fy" to "Frisian",
        "ff" to "Fulfulde",
        "gaa" to "Ga",
        "gl" to "Galician",
        "lg" to "Ganda (Luganda)",
        "ka" to "Georgian",
        "de" to "German",
        "el" to "Greek",
        "gn" to "Guarani",
        "gu" to "Gujarati",
        "ht" to "Haitian Creole",
        "cnh" to "Hakha Chin",
        "ha" to "Hausa",
        "haw" to "Hawaiian",
        "iw" to "Hebrew",
        "hil" to "Hiligaynon",
        "hi" to "Hindi",
        "hmn" to "Hmong",
        "hu" to "Hungarian",
        "hrx" to "Hunsrik",
        "is" to "Icelandic",
        "ig" to "Igbo",
        "ilo" to "Iloko",
        "id" to "Indonesian",
        "ga" to "Irish",
        "it" to "Italian",
        "ja" to "Japanese",
        "jw" to "Javanese",
        "kn" to "Kannada",
        "pam" to "Kapampangan",
        "kk" to "Kazakh",
        "km" to "Khmer",
        "cgg" to "Kiga",
        "rw" to "Kinyarwanda",
        "ktu" to "Kituba",
        "gom" to "Konkani",
        "ko" to "Korean",
        "kri" to "Krio",
        "ku" to "Kurdish (Kurmanji)",
        "ckb" to "Kurdish (Sorani)",
        "ky" to "Kyrgyz",
        "lo" to "Lao",
        "ltg" to "Latgalian",
        "la" to "Latin",
        "lv" to "Latvian",
        "lij" to "Ligurian",
        "li" to "Limburgan",
        "ln" to "Lingala",
        "lt" to "Lithuanian",
        "lmo" to "Lombard",
        "luo" to "Luo",
        "lb" to "Luxembourgish",
        "mk" to "Macedonian",
        "mai" to "Maithili",
        "mak" to "Makassar",
        "mg" to "Malagasy",
        "ms" to "Malay",
        "ms-Arab" to "Malay (Jawi)",
        "ml" to "Malayalam",
        "mt" to "Maltese",
        "mi" to "Maori",
        "mr" to "Marathi",
        "chm" to "Meadow Mari",
        "mni-Mtei" to "Meiteilon (Manipuri)",
        "min" to "Minang",
        "lus" to "Mizo",
        "mn" to "Mongolian",
        "my" to "Myanmar (Burmese)",
        "nr" to "Ndebele (South)",
        "new" to "Nepalbhasa (Newari)",
        "ne" to "Nepali",
        "nso" to "Northern Sotho (Sepedi)",
        "no" to "Norwegian",
        "nus" to "Nuer",
        "oc" to "Occitan",
        "or" to "Odia (Oriya)",
        "om" to "Oromo",
        "pag" to "Pangasinan",
        "pap" to "Papiamento",
        "ps" to "Pashto",
        "fa" to "Persian",
        "pl" to "Polish",
        "pt" to "Portuguese",
        "pt-PT" to "Portuguese (Portugal)",
        "pt-BR" to "Portuguese (Brazil)",
        "pa" to "Punjabi",
        "pa-Arab" to "Punjabi (Shahmukhi)",
        "qu" to "Quechua",
        "rom" to "Romani",
        "ro" to "Romanian",
        "rn" to "Rundi",
        "ru" to "Russian",
        "sm" to "Samoan",
        "sg" to "Sango",
        "sa" to "Sanskrit",
        "gd" to "Scots Gaelic",
        "sr" to "Serbian",
        "st" to "Sesotho",
        "crs" to "Seychellois Creole",
        "shn" to "Shan",
        "sn" to "Shona",
        "scn" to "Sicilian",
        "szl" to "Silesian",
        "sd" to "Sindhi",
        "si" to "Sinhala (Sinhalese)",
        "sk" to "Slovak",
        "sl" to "Slovenian",
        "so" to "Somali",
        "es" to "Spanish",
        "su" to "Sundanese",
        "sw" to "Swahili",
        "ss" to "Swati",
        "sv" to "Swedish",
        "tg" to "Tajik",
        "ta" to "Tamil",
        "tt" to "Tatar",
        "te" to "Telugu",
        "tet" to "Tetum",
        "th" to "Thai",
        "ti" to "Tigrinya",
        "ts" to "Tsonga",
        "tn" to "Tswana",
        "tr" to "Turkish",
        "tk" to "Turkmen",
        "ak" to "Twi (Akan)",
        "uk" to "Ukrainian",
        "ur" to "Urdu",
        "ug" to "Uyghur",
        "uz" to "Uzbek",
        "vi" to "Vietnamese",
        "cy" to "Welsh",
        "xh" to "Xhosa",
        "yi" to "Yiddish",
        "yo" to "Yoruba",
        "yua" to "Yucatec Maya",
        "zu" to "Zulu"
    )
}
