name: Build WhatsApp

on:
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties
            gradle/libs.versions.toml
            **/gradle.properties

      - name: Write key
        env:
          KEY_STORE: ${{ secrets.KEY_STORE }}
        run: |
          if [ ! -z "$KEY_STORE" ]; then
          echo androidStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
          echo androidKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
          echo androidKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
          echo androidStoreFile='key.jks' >> gradle.properties
          echo "$KEY_STORE" | base64 --decode > key.jks
          fi

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build WhatsApp Release
        run: ./gradlew assembleWhatsappRelease

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: WaEnhancer
          path: app/build/outputs/apk/whatsapp/release/WaEnhancer*.apk
